/*
    this file is used to store variable which we use in our whole project at different locations ( Something Like global Variable )
    we do this to make our code clean
*/

export const IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";
// export const SWIGGY_PUBLIC_API =
  // "https://www.swiggy.com/dapi/restaurants/list/v5?lat=28.627981&lng=77.3648567&page_type=DESKTOP_WEB_LISTING";
  // 13.083592280167409, 80.21448667920546
export const SWIGGY_PUBLIC_API =
  "https://www.swiggy.com/dapi/restaurants/list/v5?";
  //not working anymore
export const SWIGGY_MENU_API =
  "https://www.swiggy.com/dapi/menu/v4/full?lat=28.627981&lng=77.3648567&menuId="; 
//working  
export const SWIGGY_MENU_API_2 =
  "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=28.627981&lng=77.3648567&restaurantId=";   

// export const IMG_CDN_URL =
//   "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";
// export const SWIGGY_PUBLIC_API =
//   "https://www.swiggy.com/dapi/restaurants/list/v5?lat=28.627981&lng=77.3648567&page_type=DESKTOP_WEB_LISTING";
// export const SWIGGY_MENU_API =
//   "https://www.swiggy.com/dapi/menu/v4/full?lat=28.627981&lng=77.3648567&menuId=";   






// export const restaurantsList = [
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "61736",
//       name: "Chawlas Tandoori Junction Exp.",
//       uuid: "48a46550-9061-49e1-9ded-231132362c7d",
//       city: "10459",
//       area: "Sector 72",
//       totalRatingsString: "500+ ratings",
//       cloudinaryImageId: "mnrvwwovgoqolkhg7vjz",
//       cuisines: ["North Indian", "Chinese", "Mughlai", "Kebabs", "Biryani"],
//       tags: [],
//       costForTwo: 50000,
//       costForTwoString: "₹500 FOR TWO",
//       deliveryTime: 40,
//       minDeliveryTime: 40,
//       maxDeliveryTime: 40,
//       slaString: "40 MINS",
//       lastMileTravel: 7.599999904632568,
//       slugs: {
//         restaurant: "chawlas-tandoori-junction-sector-72-golf-course",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "Harishchand Complex, Near JM Aroma society Axis bank (ATM), Sarfabad, Sector 73.",
//       locality: "",
//       parentId: 13726,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5871741~p=1~eid=00000186-2c4a-ce5d-1a6d-645b00ad010e",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "7.5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "61736",
//         deliveryTime: 40,
//         minDeliveryTime: 40,
//         maxDeliveryTime: 40,
//         lastMileTravel: 7.599999904632568,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.2",
//       totalRatings: 500,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "380988",
//       name: "Keventers Ice Cream",
//       uuid: "1dd27651-1b88-403e-8110-dc3f94049a59",
//       city: "10459",
//       area: "Ghaziabad",
//       totalRatingsString: "20+ ratings",
//       cloudinaryImageId: "9c48cf6a2cb98312346ec3c4aa12af8e",
//       cuisines: ["Ice Cream", "Desserts"],
//       tags: [],
//       costForTwo: 20000,
//       costForTwoString: "₹200 FOR TWO",
//       deliveryTime: 19,
//       minDeliveryTime: 19,
//       maxDeliveryTime: 19,
//       slaString: "19 MINS",
//       lastMileTravel: 2.5999999046325684,
//       slugs: {
//         restaurant: "keventers-ice-creamery-shipra-mall-indirapuram",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "Shop No. G-17, Ground Floor Gc Grand Street, Plot No 2C, Vaibhav Khand Indrapuram, Ghaziabad Nagar Nigam Zone-5, Ghaziabad (Uttar Pradesh) -201010",
//       locality: "Indirapuram",
//       parentId: 272044,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "2.5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "380988",
//         deliveryTime: 19,
//         minDeliveryTime: 19,
//         maxDeliveryTime: 19,
//         lastMileTravel: 2.5999999046325684,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.0",
//       totalRatings: 20,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "19006",
//       name: "221b Baker Street",
//       uuid: "91d5c8a7-06b8-48c6-affe-31550c8c752b",
//       city: "10459",
//       area: "Sector 62",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "lt9o3twazq8jv5fxgwbe",
//       cuisines: ["Desserts", "Bakery"],
//       tags: [],
//       costForTwo: 25000,
//       costForTwoString: "₹250 FOR TWO",
//       deliveryTime: 19,
//       minDeliveryTime: 19,
//       maxDeliveryTime: 19,
//       slaString: "19 MINS",
//       lastMileTravel: 2.5,
//       slugs: {
//         restaurant: "baker-street-sector-62-noida-sector-62",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address: "PG 30, TOT Mall, Sector 62, Noida",
//       locality: "Tot Mall",
//       parentId: 2664,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "2.5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "19006",
//         deliveryTime: 19,
//         minDeliveryTime: 19,
//         maxDeliveryTime: 19,
//         lastMileTravel: 2.5,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.1",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "33861",
//       name: "Rasoi Deliver",
//       uuid: "a77cfb1e-a50c-441f-86e3-23ae4a931c5c",
//       city: "10459",
//       area: "Indirapuram",
//       totalRatingsString: "500+ ratings",
//       cloudinaryImageId: "gjnwk48xtjwvad87fbho",
//       cuisines: ["North Indian", "Chinese"],
//       tags: [],
//       costForTwo: 30000,
//       costForTwoString: "₹300 FOR TWO",
//       deliveryTime: 26,
//       minDeliveryTime: 26,
//       maxDeliveryTime: 26,
//       slaString: "26 MINS",
//       lastMileTravel: 2.5,
//       slugs: {
//         restaurant: "rasoi-deliver-indirapuram-indirapuram",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address: "K-4, Windsor Street, Vaibhav Khand, Indirapuram",
//       locality: "Windsor Street Market",
//       parentId: 4132,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "FLAT150 off",
//         shortDescriptionList: [
//           {
//             meta: "FLAT150 off | Use FLATDEAL",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "FLAT150 off | Use FLATDEAL",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "₹150 OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use FLATDEAL",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "FLAT150 off | Use FLATDEAL",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5908800~p=4~eid=00000186-2c4a-ce5d-1a6d-645c00ad0445",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "2.5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "33861",
//         deliveryTime: 26,
//         minDeliveryTime: 26,
//         maxDeliveryTime: 26,
//         lastMileTravel: 2.5,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.0",
//       totalRatings: 500,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "49880",
//       name: "Delhi Biryani Hut",
//       uuid: "7cc2c09b-dcf3-45e4-85f3-96acae9f4d3a",
//       city: "10459",
//       area: "Sector 62",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "epzdvycbqbhhsv4xs9vi",
//       cuisines: ["Mughlai", "Biryani"],
//       tags: [],
//       costForTwo: 20000,
//       costForTwoString: "₹200 FOR TWO",
//       deliveryTime: 19,
//       minDeliveryTime: 19,
//       maxDeliveryTime: 19,
//       slaString: "19 MINS",
//       lastMileTravel: 1.7999999523162842,
//       slugs: {
//         restaurant: "delhi-biryani-hut-sector-62-test-siddardha",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "RN-3-B, Opposite Corporation Bank, Near Fortis Hospital, Sector 62, Noida",
//       locality: "",
//       parentId: 13890,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "1.7 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "49880",
//         deliveryTime: 19,
//         minDeliveryTime: 19,
//         maxDeliveryTime: 19,
//         lastMileTravel: 1.7999999523162842,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "3.7",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "524942",
//       name: "Theobroma",
//       uuid: "da183495-d7cf-465c-87a1-511860335f0d",
//       city: "10459",
//       area: "Ghaziabad",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "oyyuiofe34uoho1xpyxb",
//       cuisines: ["Bakery", "Desserts"],
//       tags: [],
//       costForTwo: 60000,
//       costForTwoString: "₹600 FOR TWO",
//       deliveryTime: 20,
//       minDeliveryTime: 20,
//       maxDeliveryTime: 20,
//       slaString: "20 MINS",
//       lastMileTravel: 3.799999952316284,
//       slugs: {
//         restaurant: "theobroma-indirapuram-indirapuram",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "Shop No G-11(G.F) GC Grand Street Vaibhav Khand Indirapuram GZB 201014",
//       locality: "Indirapuram",
//       parentId: 1040,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "10% off",
//         shortDescriptionList: [
//           {
//             meta: "10% off | Use SPECIALS",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "10% off on select items | Use code SPECIALS",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "10% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use SPECIALS",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "10% off on select items | Use code SPECIALS",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "3.7 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "524942",
//         deliveryTime: 20,
//         minDeliveryTime: 20,
//         maxDeliveryTime: 20,
//         lastMileTravel: 3.799999952316284,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.6",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "49199",
//       name: "The Punjabi Junction",
//       uuid: "f8528b05-656e-43ea-95be-6418528b04e3",
//       city: "10459",
//       area: "Indirapuram",
//       totalRatingsString: "500+ ratings",
//       cloudinaryImageId: "xmmqtwxqpvy4xhc3gqzl",
//       cuisines: ["North Indian", "Mughlai"],
//       tags: [],
//       costForTwo: 30000,
//       costForTwoString: "₹300 FOR TWO",
//       deliveryTime: 29,
//       minDeliveryTime: 29,
//       maxDeliveryTime: 29,
//       slaString: "29 MINS",
//       lastMileTravel: 3,
//       slugs: {
//         restaurant: "the-punjabi-junction-indirapuram-indirapuram",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "SE- 45 , Basement , opposite Niti Khand 3 Gate no 1 , plot no 12 ( A) , adjustment to Flavours of Chakhna restaurant  Jaipuria Sunrise Plaza , Indirapuram- 201014 ( Ahinsa Khand )",
//       locality: "Jaipuria Sunrise Green",
//       parentId: 13471,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use GUILTFREE",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹150 | Use code GUILTFREE",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use GUILTFREE",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹150 | Use code GUILTFREE",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5838620~p=7~eid=00000186-2c4a-ce5d-1a6d-645d00ad0778",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "3 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "49199",
//         deliveryTime: 29,
//         minDeliveryTime: 29,
//         maxDeliveryTime: 29,
//         lastMileTravel: 3,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.0",
//       totalRatings: 500,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "183389",
//       name: "NIC Ice Creams",
//       uuid: "ceda7714-eacf-436c-80a8-6f5f622de179",
//       city: "10459",
//       area: "Ghaziabad",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "hzmaz23zxtgxexnlwngu",
//       cuisines: ["Desserts", "Ice Cream"],
//       tags: [],
//       costForTwo: 12000,
//       costForTwoString: "₹120 FOR TWO",
//       deliveryTime: 20,
//       minDeliveryTime: 20,
//       maxDeliveryTime: 20,
//       slaString: "20 MINS",
//       lastMileTravel: 3,
//       slugs: {
//         restaurant: "nic-natural-ice-creams-sunrise-greens-indirapuram",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "SE-130, JAIPURIA SUNRISE GREENS, PLOT NO 12(A),  AHINSHA KHAND INDIRAPURAM, GHAZIABAD UP.",
//       locality: "Indirapuram",
//       parentId: 6249,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "3 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "183389",
//         deliveryTime: 20,
//         minDeliveryTime: 20,
//         maxDeliveryTime: 20,
//         lastMileTravel: 3,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.7",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "430487",
//       name: "Bake The Cake (BTC)",
//       uuid: "07499b64-a609-45e8-95d2-d7026f5ddd7b",
//       city: "10459",
//       area: "Ghaziabad",
//       totalRatingsString: "Too Few Ratings",
//       cloudinaryImageId: "prkwwq3bf5wsmizzqpsg",
//       cuisines: ["Bakery", "Desserts"],
//       tags: [],
//       costForTwo: 30000,
//       costForTwoString: "₹300 FOR TWO",
//       deliveryTime: 21,
//       minDeliveryTime: 21,
//       maxDeliveryTime: 21,
//       slaString: "21 MINS",
//       lastMileTravel: 3,
//       slugs: {
//         restaurant: "bake-the-cake-(btc)-indirapuram-indirapuram",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address: "SC 59A JAIPURIA SUNRISE PLAZA INDIRAPURAM GHAZIABAD -201014",
//       locality: "Indirapuram",
//       parentId: 259647,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "3 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "430487",
//         deliveryTime: 21,
//         minDeliveryTime: 21,
//         maxDeliveryTime: 21,
//         lastMileTravel: 3,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "--",
//       totalRatings: 0,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "574401",
//       name: "Kake Da Hotel",
//       uuid: "cb31ee80-53db-4bd6-b70e-881cc7d6d887",
//       city: "10459",
//       area: "Indirapuram",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "z6abqnlwcjvljwepontb",
//       cuisines: [
//         "North Indian",
//         "Biryani",
//         "Tandoor",
//         "Snacks",
//         "Chinese",
//         "Mughlai",
//       ],
//       tags: [],
//       costForTwo: 50000,
//       costForTwoString: "₹500 FOR TWO",
//       deliveryTime: 27,
//       minDeliveryTime: 27,
//       maxDeliveryTime: 27,
//       slaString: "27 MINS",
//       lastMileTravel: 2.299999952316284,
//       slugs: {
//         restaurant: "kake-da-hotel-indirapuram-indirapuram-2",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "Shop no. 28 , windsor street , windsor park , Indirapuram , Ghaziabad , UP 201014",
//       locality: "Windsor Street Market",
//       parentId: 113762,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5847103~p=10~eid=00000186-2c4a-ce5d-1a6d-645e00ad0a0c",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "2.2 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "574401",
//         deliveryTime: 27,
//         minDeliveryTime: 27,
//         maxDeliveryTime: 27,
//         lastMileTravel: 2.299999952316284,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.1",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "355356",
//       name: "Grameen Kulfi",
//       uuid: "76f6d231-f9df-46e5-8706-ce8542d4db4a",
//       city: "10459",
//       area: "Indirapuram",
//       totalRatingsString: "20+ ratings",
//       cloudinaryImageId: "bonyktezt5gx95vunmal",
//       cuisines: ["Desserts", "Ice Cream"],
//       tags: [],
//       costForTwo: 12000,
//       costForTwoString: "₹120 FOR TWO",
//       deliveryTime: 21,
//       minDeliveryTime: 21,
//       maxDeliveryTime: 21,
//       slaString: "21 MINS",
//       lastMileTravel: 3,
//       slugs: {
//         restaurant: "grameen-kulfi-sunrise-greens-indirapuram",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "SE-130, JAIPURIA SUNRISE GREENS, PLOT NO 12(A),  AHINSHA KHAND INDIRAPURAM, GHAZIABAD UP.",
//       locality: "Jaipuria Sunrise Green",
//       parentId: 12175,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "3 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "355356",
//         deliveryTime: 21,
//         minDeliveryTime: 21,
//         maxDeliveryTime: 21,
//         lastMileTravel: 3,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.9",
//       totalRatings: 20,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "42808",
//       name: "Rollsking",
//       uuid: "92bb275f-c913-4466-a9e3-86247b3cc094",
//       city: "10459",
//       area: "Sector 62",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "rpoiziw5dhc1h59y5tje",
//       cuisines: ["North Indian", "Fast Food", "Beverages"],
//       tags: [],
//       costForTwo: 25000,
//       costForTwoString: "₹250 FOR TWO",
//       deliveryTime: 21,
//       minDeliveryTime: 21,
//       maxDeliveryTime: 21,
//       slaString: "21 MINS",
//       lastMileTravel: 2,
//       slugs: {
//         restaurant: "rollsking-sector-62-test-siddardha",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address: "RN 11 Sector 62 Noida",
//       locality: "",
//       parentId: 4697,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "40% off",
//         shortDescriptionList: [
//           {
//             meta: "40% off | Use GUILTFREE",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "40% off up to ₹100 | Use code GUILTFREE",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "40% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use GUILTFREE",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "40% off up to ₹100 | Use code GUILTFREE",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "2 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "42808",
//         deliveryTime: 21,
//         minDeliveryTime: 21,
//         maxDeliveryTime: 21,
//         lastMileTravel: 2,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.1",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "612144",
//       name: "Hudson Chopsticks",
//       uuid: "a9b75c98-0aae-43eb-beb4-b6c0b4972f1e",
//       city: "10459",
//       area: "Sector 62",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "tbdpvuqxnqfmotmsqlqj",
//       cuisines: [
//         "Chinese",
//         "Pan-Asian",
//         "Oriental",
//         "Japanese",
//         "Thai",
//         "Asian",
//         "Seafood",
//         "Barbecue",
//         "Indonesian",
//         "Grill",
//       ],
//       tags: [],
//       costForTwo: 30000,
//       costForTwoString: "₹300 FOR TWO",
//       deliveryTime: 29,
//       minDeliveryTime: 29,
//       maxDeliveryTime: 29,
//       slaString: "29 MINS",
//       lastMileTravel: 1.100000023841858,
//       slugs: {
//         restaurant: "hudson-chopsticks-sector-64-sector-64",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "Plot No. A-40, Unit No. 4 on the ground floor, Tower A, I-THUM Building, Sector 62, Noida (Opposite electronic City metro station).201309",
//       locality: "A Block",
//       parentId: 7129,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5910476~p=13~eid=00000186-2c4a-ce5d-1a6d-645f00ad0d3a",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "1.1 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "612144",
//         deliveryTime: 29,
//         minDeliveryTime: 29,
//         maxDeliveryTime: 29,
//         lastMileTravel: 1.100000023841858,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.2",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "342192",
//       name: "KHAN BIRYANI CENTER",
//       uuid: "4d385942-5d1b-4b37-9c3e-1b9ece4a701d",
//       city: "10459",
//       area: "Sector 62",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "dn01p3cekdqmymcfej5f",
//       cuisines: ["Biryani", "Mughlai"],
//       tags: [],
//       costForTwo: 20000,
//       costForTwoString: "₹200 FOR TWO",
//       deliveryTime: 21,
//       minDeliveryTime: 21,
//       maxDeliveryTime: 21,
//       slaString: "21 MINS",
//       lastMileTravel: 1.7000000476837158,
//       slugs: {
//         restaurant: "khan-biryani-center-sector-64-sector-64",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "RN-40, RASULPUR NAVADA, B-BLOCK, SECTOR-62, NOIDA,  Gautam Buddha Nagar , UttarPradesh-201309",
//       locality: "B Block",
//       parentId: 117157,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "1.7 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "342192",
//         deliveryTime: 21,
//         minDeliveryTime: 21,
//         maxDeliveryTime: 21,
//         lastMileTravel: 1.7000000476837158,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "3.8",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "260479",
//       name: "The Tandoori Tales",
//       uuid: "5edb49f3-e279-4920-ab09-ad272940a44a",
//       city: "10459",
//       area: "Sector 72",
//       totalRatingsString: "500+ ratings",
//       cloudinaryImageId: "tn0duqvypsma052chret",
//       cuisines: ["North Indian", "Mughlai", "Chinese", "Kebabs", "Biryani"],
//       tags: [],
//       costForTwo: 50000,
//       costForTwoString: "₹500 FOR TWO",
//       deliveryTime: 40,
//       minDeliveryTime: 40,
//       maxDeliveryTime: 40,
//       slaString: "40 MINS",
//       lastMileTravel: 7.599999904632568,
//       slugs: {
//         restaurant: "tandoori-tales-sector-50-sector-50",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "Harishchand Complex, Near JM Aroma society Axis bank (ATM), Sarfabad, Sector 73.",
//       locality: "",
//       parentId: 404924,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5871743~p=16~eid=00000186-2c4a-ce5d-1a6d-646000ad102f",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "7.5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "260479",
//         deliveryTime: 40,
//         minDeliveryTime: 40,
//         maxDeliveryTime: 40,
//         lastMileTravel: 7.599999904632568,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.2",
//       totalRatings: 500,
//       new: false,
//     },
//     subtype: "basic",
//   },
// ];
